import {chromium} from '/home/samashech/Documents/Pixco/node_modules/playwright/index.mjs';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {pageAction}=await import('data:text/javascript;base64,'+Buffer.from(await readFile(new URL('../browser-extension/page.js',import.meta.url))).toString('base64'));
const browser=await chromium.launch({executablePath:'/usr/bin/brave-origin',headless:true,args:['--no-sandbox']});
try{
 const page=await browser.newPage();
 await page.route('https://www.google.com/**',r=>r.fulfill({contentType:'text/html',body:`<form action="/search"><textarea name="q"></textarea><button type="submit">Google Search</button></form><div id="tads"><a href="https://example.com/ad"><h3>Sponsored first</h3></a></div><div id="search"><a href="https://example.com/normal"><h3>Normal second</h3></a></div>`}));
 await page.route('https://example.com/**',r=>r.fulfill({contentType:'text/html',body:'<h1>Selected result</h1>'}));
 await page.goto('https://www.google.com');
 await page.evaluate(pageAction,{op:'search',site:'google',query:'rock and roll'});
 await page.waitForURL('**/search?q=rock+and+roll');
 await page.evaluate(pageAction,{op:'result',index:1});
 await page.waitForURL('https://example.com/ad');
 console.log('PASS: Google field submission and first sponsored result');
 await page.route('https://www.youtube.com/**',r=>r.fulfill({contentType:'text/html',body:'<form action="/results"><input name="search_query"><button class="ytSearchboxComponentSearchButton">Search</button></form>'}));
 await page.goto('https://www.youtube.com');
 await page.evaluate(pageAction,{op:'search',site:'youtube',query:'bbs'});
 await page.waitForURL('**/results?search_query=bbs');
 console.log('PASS: YouTube search stays on YouTube');
 await page.setContent('<label>Name<input></label><button onclick="this.textContent=\'Done\'">Save</button>');
 await page.evaluate(pageAction,{op:'fill',target:'Name',text:'hello'});
 assert.equal(await page.locator('input').inputValue(),'hello');
 await page.evaluate(pageAction,{op:'click',target:'Save'});
 assert.equal(await page.locator('button').textContent(),'Done');
 await page.setContent('<span id=label>Search</span><input aria-labelledby=label><button aria-label=Search>Search</button>');
 await page.evaluate(pageAction,{op:'click',target:'Search',role:'field'});
 assert.equal(await page.locator('input').evaluate(e=>document.activeElement===e),true);
 await page.evaluate(pageAction,{op:'click',target:'Search button'});
 await page.setContent('<button>Save</button><button>Save</button>');
 await assert.rejects(page.evaluate(pageAction,{op:'click',target:'Save'}),/More than one/);
 console.log('PASS: named controls, field verification and ambiguous match rejection');
 await page.setContent(`<div data-testid="tracklist-row"><a href="/track/1">God's Plan</a><button aria-label="Play God's Plan" onclick="document.querySelector('#transport').setAttribute('aria-label','Pause')">Play</button></div><button id="transport" data-testid="control-button-playpause" aria-label="Play"></button><a data-testid="context-item-link">God's Plan</a>`);
 await page.evaluate(pageAction,{op:'play',query:"God's Plan"});
 assert.equal((await page.evaluate(pageAction,{op:'playing',query:"God's Plan"})).playing,true);
 console.log('PASS: matching Spotify track activation and playback-state check');
 await page.setContent(`<div data-testid="tracklist-row"><a href="/track/wrong">Unrelated song</a><a href="/artist/other">Someone else</a><button aria-label="Play unrelated">Play</button></div><div data-testid="tracklist-row"><a href="/track/baby">Baby</a><a href="/artist/justin">Justin Bieber</a><button aria-label="Play Baby" onclick="this.dataset.played='yes'">Play</button></div>`);
 const selected=await page.evaluate(pageAction,{op:'play',query:'justin bieber',mode:'artist'});
 assert.equal(selected.track,'Baby');
 assert.equal(await page.locator('[aria-label="Play Baby"]').getAttribute('data-played'),'yes');
 await page.route('https://github.com/**',r=>r.fulfill({contentType:'text/html',body:`<meta name="user-login" content="fixture-user"><form><input id="your-repos-filter" name="q"></form><div id="user-repositories-list"><h3><a href="/fixture-user/ClickyAI" itemprop="name codeRepository">ClickyAI</a></h3></div>`}));
 await page.goto('https://github.com/fixture-user?tab=repositories');
 assert.equal((await page.evaluate(pageAction,{op:'github_user'})).user,'fixture-user');
 assert.equal((await page.evaluate(pageAction,{op:'github_repository',query:'clickyai'})).url,'https://github.com/fixture-user/ClickyAI');
 console.log('PASS: artist matches track artist, and GitHub resolves repository within signed-in owner');
}finally{await browser.close();}
